import { createServiceRoleClient } from '@/lib/supabase/server';
import { getResend } from '@/lib/resend';
import { NextRequest, NextResponse } from 'next/server';
import WaitlistWelcome from '@/emails/WaitlistWelcome';
import WaitlistTeacher from '@/emails/WaitlistTeacher';
import WaitlistParent from '@/emails/WaitlistParent';

function getEmailForRole(role: string, name?: string, referralCode?: string) {
  switch (role) {
    case 'teacher':
      return {
        subject: "You're on the list — built for educators like you",
        react: WaitlistTeacher({ name, referralCode }),
      };
    case 'parent':
      return {
        subject: "You're on the list — we're building something your child will love",
        react: WaitlistParent({ name, referralCode }),
      };
    default:
      return {
        subject: "You're on the list — welcome to Agathon",
        react: WaitlistWelcome({ name, referralCode }),
      };
  }
}

// Fallback referral code generator (matches DB pattern)
function generateReferralCode(): string {
  const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  let code = '';
  for (let i = 0; i < 8; i++) {
    code += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return code;
}

// Fallback referral tracking via direct queries (if RPC function is unavailable)
async function recordReferralDirect(
  supabase: ReturnType<typeof createServiceRoleClient>,
  referralCode: string,
  newWaitlistId: string
) {
  const { data: referrer, error: lookupError } = await supabase
    .from('waitlist')
    .select('id, referral_count')
    .eq('referral_code', referralCode)
    .single();

  if (lookupError || !referrer) {
    console.warn('[referral-direct] Code not found:', referralCode, lookupError?.message);
    return;
  }

  if (referrer.id === newWaitlistId) {
    console.warn('[referral-direct] Self-referral prevented');
    return;
  }

  // Set referred_by on the new entry
  const { error: updateRefError } = await supabase
    .from('waitlist')
    .update({ referred_by: referrer.id })
    .eq('id', newWaitlistId)
    .is('referred_by', null);

  if (updateRefError) {
    console.error('[referral-direct] Failed to set referred_by:', updateRefError.message);
  }

  // Increment referral count on the referrer
  const { error: updateCountError } = await supabase
    .from('waitlist')
    .update({ referral_count: (referrer.referral_count || 0) + 1 })
    .eq('id', referrer.id);

  if (updateCountError) {
    console.error('[referral-direct] Failed to increment count:', updateCountError.message);
  } else {
    console.log('[referral-direct] Recorded referral for referrer:', referrer.id);
  }
}

export async function POST(request: NextRequest) {
  try {
    const { email, name, role, ref } = await request.json();

    if (!email || !email.includes('@')) {
      return NextResponse.json(
        { error: 'Valid email is required' },
        { status: 400 }
      );
    }

    if (!name || typeof name !== 'string' || !name.trim()) {
      return NextResponse.json(
        { error: 'Name is required' },
        { status: 400 }
      );
    }

    const supabase = createServiceRoleClient();

    // Check if email already exists
    const { data: existing } = await supabase
      .from('waitlist')
      .select('id, referral_code')
      .eq('email', email.toLowerCase())
      .single();

    if (existing) {
      // Ensure existing user has a referral code
      let existingCode = existing.referral_code;
      if (!existingCode) {
        existingCode = generateReferralCode();
        await supabase
          .from('waitlist')
          .update({ referral_code: existingCode })
          .eq('id', existing.id);
      }
      return NextResponse.json(
        { message: "You're already on the waitlist!", alreadyExists: true, referralCode: existingCode },
        { status: 200 }
      );
    }

    // Insert new waitlist entry (referral_code should be auto-generated by DB trigger)
    const { data: newEntry, error } = await supabase
      .from('waitlist')
      .insert({
        email: email.toLowerCase(),
        name: name || null,
        role: role || 'student',
      })
      .select('id, referral_code')
      .single();

    if (error || !newEntry) {
      console.error('Waitlist insert error:', error);
      return NextResponse.json(
        { error: 'Failed to join waitlist' },
        { status: 500 }
      );
    }

    // Ensure referral code exists (fallback if DB trigger didn't fire)
    let referralCode = newEntry.referral_code;
    if (!referralCode) {
      console.warn('[waitlist] DB trigger did not generate referral_code, using JS fallback');
      referralCode = generateReferralCode();
      const { error: codeUpdateError } = await supabase
        .from('waitlist')
        .update({ referral_code: referralCode })
        .eq('id', newEntry.id);
      if (codeUpdateError) {
        console.error('[waitlist] Failed to set fallback referral code:', codeUpdateError.message);
      }
    }

    // Track referral if ref code was provided
    if (ref && typeof ref === 'string') {
      const cleanedRef = ref.replace(/[-\s]/g, '').toUpperCase();
      console.log('[waitlist] Tracking referral:', { ref: cleanedRef, newId: newEntry.id });

      try {
        const { data: referralResult, error: referralError } = await supabase.rpc('record_referral', {
          p_referral_code: cleanedRef,
          p_new_waitlist_id: newEntry.id,
        });

        if (referralError) {
          console.error('[waitlist] RPC record_referral failed, trying direct:', referralError.message);
          await recordReferralDirect(supabase, cleanedRef, newEntry.id);
        } else {
          const result = Array.isArray(referralResult) ? referralResult[0] : referralResult;
          if (result && !result.success) {
            console.warn('[waitlist] Referral not recorded:', result.error_message);
          } else {
            console.log('[waitlist] Referral recorded via RPC');
          }
        }
      } catch (rpcErr) {
        console.error('[waitlist] RPC exception, trying direct:', rpcErr);
        await recordReferralDirect(supabase, cleanedRef, newEntry.id);
      }
    }

    // Send role-specific welcome email with referral link
    const userRole = role || 'student';
    const { subject, react } = getEmailForRole(userRole, name.trim(), referralCode);

    const resend = await getResend();
    const { error: emailError } = await resend.emails.send({
      from: 'Agathon <send@mail.agathon.app>',
      replyTo: 'rushil@agathon.app',
      to: email.toLowerCase(),
      subject,
      react,
    });

    if (emailError) {
      console.error('Email send error:', emailError);
    }

    return NextResponse.json(
      {
        message: "You're on the list! We'll be in touch soon.",
        success: true,
        referralCode,
      },
      { status: 200 }
    );
  } catch (error) {
    console.error('Waitlist API error:', error);
    return NextResponse.json(
      { error: 'Something went wrong' },
      { status: 500 }
    );
  }
}
